version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "simplify-makefile.patch",
]
SPDX-FileCopyrightText = "astyle contributors"
SPDX-License-Identifier = "LGPL-3.0-only"
