["lib32-readline:base"]
source = "htmlparser"
url = "https://cgit.git.savannah.gnu.org/cgit/readline.git/commit/"
xpath = "//div[@class='commit-subject']"
from_pattern = '[rR]eadline-([\d.]+)(\s+patch\s+(\d+))?.*'
to_pattern = '\1\2'

[lib32-readline]
source = "combiner"
from = ["lib32-readline:base"]
format = "$1"
from_pattern = " patch "
to_pattern = "."
