version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "use-system-zstd.patch",
    "strip-rpath.patch",
]
SPDX-FileCopyrightText = "basis-universal contributors"
SPDX-License-Identifier = "Apache-2.0"
