version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "fix-install.patch",
    "__init__.py",
]
SPDX-FileCopyrightText = "lib3mf contributors"
SPDX-License-Identifier = "BSD-2-Clause"
