version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "nix.conf",
    "sysusers.conf",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "perl-vendor-path.patch",
    "remove-unused-sh-files.patch",
    "skip-functional-tests.patch",
]
SPDX-FileCopyrightText = "nix contributors"
SPDX-License-Identifier = "LGPL-2.1-only"
