version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "sysusers.conf",
    "tmpfiles.conf",
    "systemd.service",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "env-overrides.patch",
]
SPDX-FileCopyrightText = "vaultwarden contributors"
SPDX-License-Identifier = "AGPL-3.0-only"
