version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "gradle-repro.patch",
    "wrapper.sh",
    "shattered-pixel-dungeon.desktop",
]
SPDX-FileCopyrightText = "shattered-pixel-dungeon contributors"
SPDX-License-Identifier = "GPL-3.0-only"
