version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    ".nvchecker.toml",
    "vcpkg.install",
    "vcpkg.sh",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "fmt-12.patch",
]
SPDX-FileCopyrightText = "vcpkg contributors"
SPDX-License-Identifier = "MIT"
