version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "templatify-build-date.patch",
]
SPDX-FileCopyrightText = "ft2-clone contributors"
SPDX-License-Identifier = "BSD-3-Clause"
