version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "beet",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "fix-failing-tests.patch",
    "fix-python-3.14-compatibility.patch",
]
SPDX-FileCopyrightText = "beets contributors"
SPDX-License-Identifier = "MIT"
