version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "0001-Fix-configuration-to-point-to-installed-files.patch",
    "0002-Set-default-project-directory-to-package-provided-di.patch",
    "0003-Exclude-force-includes-in-wheel-builds-to-fix-duplic.patch",
]
SPDX-FileCopyrightText = "nominatim contributors"
SPDX-License-Identifier = "GPL-2.0-only"
