version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "unbreak-svt-av1-4-build.patch",
]
SPDX-FileCopyrightText = "jellyfin-ffmpeg contributors"
SPDX-License-Identifier = "GPL-3.0-only"
