version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "certs.patch",
]
SPDX-FileCopyrightText = "python-requests contributors"
SPDX-License-Identifier = "Apache-2.0"
