version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"
