version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "do-not-run-cppcheck.patch",
    "suppress-deprecated-declarations.patch",
]
SPDX-FileCopyrightText = "js80p contributors"
SPDX-License-Identifier = "GPL-3.0-only"
