version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "boost-1.86.patch",
    "boost-1.89.patch",
]
SPDX-FileCopyrightText = "openscad contributors"
SPDX-License-Identifier = "GPL-2.0-or-later"
