version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "pyproject.toml-template.patch",
    "remove-unnecessary-dependencies.patch",
]
SPDX-FileCopyrightText = "python-sphinx-prompt contributors"
SPDX-License-Identifier = "BSD-3-Clause"
