version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "nut-lowspeed-buffer-size.patch",
    "nut-no-libdummy.patch",
    "nut-openssl-1.1.patch",
    "nut-snmp-usb-order.patch",
]
SPDX-FileCopyrightText = "nut contributors"
SPDX-License-Identifier = "GPL-2.0-or-later"
