version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "ROCm-use-HIPBLAS_V2-types-and-APIs-ROCm-7-ready.patch",
    "fix-cuda13.patch",
]
SPDX-FileCopyrightText = "magma contributors"
SPDX-License-Identifier = "BSD-3-Clause"
