version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "fix-swank-loader-path.patch",
    "fix-texinfo-path.patch",
]
SPDX-FileCopyrightText = "emacs-slime contributors"
SPDX-License-Identifier = "MIT OR GPL-2.0-or-later OR LGPL-2.0-or-later"
