version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "yeet-six.patch",
]
SPDX-FileCopyrightText = "python-markdownify contributors"
SPDX-License-Identifier = "MIT"
