version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "maven-repro.patch",
    "wrapper.sh",
]
SPDX-FileCopyrightText = "cfr contributors"
SPDX-License-Identifier = "MIT"
