version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "generate-man-pages.patch",
]
SPDX-FileCopyrightText = "bibutils contributors"
SPDX-License-Identifier = "GPL-2.0-only"
