version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "use-system-curl-impersonate.patch",
    "no-download.patch",
]
SPDX-FileCopyrightText = "python-curl_cffi contributors"
SPDX-License-Identifier = "MIT"
