[firefox-spell-ru]
source = "regex"
url = "https://addons.mozilla.org/en-US/firefox/addon/russian-spellchecking-dic-3703/versions/"
regex = "russian_spellchecking_dic_3703-(\\d+\\.\\d+\\.\\d+\\.\\S+).xpi"
