version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "gnome-break-timer-onlyshowin-gnome.patch",
    "gnome-break-timer-window-icon.patch",
]
SPDX-FileCopyrightText = "gnome-break-timer contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"
