version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "add-icon-to-desktop.patch",
]
SPDX-FileCopyrightText = "racket contributors"
SPDX-License-Identifier = "Apache-2.0 OR GPL-3.0-only OR LGPL-3.0-only"
