version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "fix-version-string.patch",
]
SPDX-FileCopyrightText = "freeorion contributors"
SPDX-License-Identifier = "GPL-2.0-only"
