[material-symbols-font]
source = "manual"
# source = "cmd"
# cmd = "font-v report <(curl -s https://github.com/google/material-design-icons/raw/refs/heads/master/variablefont/MaterialSymbolsOutlined%5BFILL,GRAD,opsz,wght%5D.ttf) | tail -n1"
