version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "python-aotriton-don-t-create-a-virtualenv-and-build-triton.patch",
    "python-aotriton-use-system-pybind11.patch",
    "python-aotriton-v3src-Use-system-python-executable-instead-of-venv.patch",
]
SPDX-FileCopyrightText = "python-aotriton contributors"
SPDX-License-Identifier = "MIT"
