version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "letterpress-clear-tmpfiles.patch",
    "letterpress-dbus-activatable.patch",
    "letterpress-drop-target.patch",
    "letterpress-png-convert.patch",
    "letterpress-ref-dialog.patch",
]
SPDX-FileCopyrightText = "letterpress contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"
