version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "remove-makedepends-jq.patch",
]
SPDX-FileCopyrightText = "difftastic contributors"
SPDX-License-Identifier = "MIT"
