version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = "update_cxx20.patch"
SPDX-FileCopyrightText = "Matt Liberty"
SPDX-License-Identifier = "BSL-1.0"
comment = "Obtained from Matt Liberty"

[[annotations]]
path = [
    "cmake_version.patch",
    "remove-register.patch"
]
SPDX-FileCopyrightText = "Andreas Wendleder (gonsolo)"
SPDX-License-Identifier = "BSL-1.0"

