version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "sysusers.conf",
    "tmpfiles.conf",
    "systemd.service",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "use-correct-variables.patch",
]
SPDX-FileCopyrightText = "forgejo contributors"
SPDX-License-Identifier = "GPL-3.0-or-later"
