version = 1

[[annotations]]
path = [
    "PKGBUILD",
    ".SRCINFO",
    ".nvchecker.toml",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "pytest5.patch",
    "pytest-asyncio-failures.patch",
]
SPDX-FileCopyrightText = "python-responses contributors"
SPDX-License-Identifier = "Apache-2.0"
