version = 1

[[annotations]]
path = [
    "PKGBUILD",
    "README.md",
    "keys/**",
    ".SRCINFO",
    ".nvchecker.toml",
    "*.install",
    "*.sysusers",
    "*.tmpfiles",
    "*.logrotate",
    "*.pam",
    "*.service",
    "*.socket",
    "*.timer",
    "*.desktop",
    "*.hook",
]
SPDX-FileCopyrightText = "Arch Linux contributors"
SPDX-License-Identifier = "0BSD"

[[annotations]]
path = [
    "bun-add-cmake-option-zig-local.patch",
    "bun-fix-dangling-pointer-in-remote-debugger.patch",
    "bun-sqlite3-lib-path.diff",
]
SPDX-FileCopyrightText = "bun contributors"
SPDX-License-Identifier = "0BSD"
